AWSTemplateFormatVersion: 2010-09-09
Description: "Infraestrutura aplicação home-finance"

Parameters:
  Stage:
    Type: String
    AllowedValues:
     - dev
     - uat
     - prod
    Default: dev 

Resources:
  HomeFinanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HomeFinanceTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: Development


  ValidationLambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lambda-custom-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref ValidationTopic

  ValidationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Notification Lambda Function"
      FunctionName: finance-notification
      Handler: HomeFinance2.Validation.Function::FunctionHandler
      MemorySize: 128
      Role: !GetAtt ValidationLambdaIamRole.Arn
      Runtime: dotnet8
      Timeout: 30
      Environment:
        Variables:
          TableName: value1
      Code:
        S3Bucket: home-finance-packages
        S3Key: validation-lambda.zip
      Tags:
        - Key: keyname
          Value: value
  
  ValidationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Validation Topic"
      TopicName: "ValidationTopic"

Outputs:
  DynamoDBTable:
    Description: "Nome da tabela Dynamo"
    Value: !Ref HomeFinanceTable
    
  LambdaFunction:
    Description: "ARN da função"
    Value: !GetAtt ValidationLambda.Arn
  
  SNSTopic:
    Description: "ARN do Tópico SNS"
    Value: !Ref ValidationTopic