AWSTemplateFormatVersion: 2010-09-09
Description: "Stack para criação do banco Dynamo"

Resources:
  HomeFinanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Pk
          AttributeType: S
      KeySchema:
        - AttributeName: Pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: HomeFinanceTable

Outputs:
  HomeFinanceTableName:
    Value: !Ref HomeFinanceTable
